# Generated by Django 2.2.3 on 2019-11-25 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20191125_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 10, 26, 41, 743621, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
