# Generated by Django 2.2.3 on 2019-11-25 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20191125_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 11, 30, 32, 663739, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
