# Generated by Django 2.2.3 on 2019-11-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20191125_1930'),
        ('comments', '0002_auto_20191125_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
